package com.lop.devtools.monstera.files.beh.spawnrules.conditions

import com.google.gson.annotations.SerializedName

enum class BiomeTag {
    @SerializedName("animal")
    ANIMAL,
    @SerializedName("beach")
    BEACH,
    @SerializedName("birch")
    BIRCH,
    @SerializedName("cold")
    COLD,
    @SerializedName("dark_oak")
    DARK_OAK,
    @SerializedName("deep")
    DEEP,
    @SerializedName("desert")
    DESERT,
    @SerializedName("edge")
    EDGE,
    @SerializedName("extreme_hills")
    EXTREME_HILLS,
    @SerializedName("flower_forest")
    FLOWER_FOREST,
    @SerializedName("forest")
    FOREST,
    @SerializedName("frozen")
    FROZEN,
    @SerializedName("hills")
    HILLS,
    @SerializedName("ice")
    ICE,
    @SerializedName("ice_plains")
    ICE_PLAINS,
    @SerializedName("jungle")
    JUNGLE,
    @SerializedName("lakes")
    LAKES,
    @SerializedName("lukewarm")
    LUKEWARM,
    @SerializedName("mega")
    MEGA,
    @SerializedName("mesa")
    MESA,
    @SerializedName("monster")
    MONSTER,
    @SerializedName("mooshroom_island")
    MOOSHROOM_ISLAND,
    @SerializedName("mountain")
    MOUNTAIN,
    @SerializedName("mutated")
    MUTATED,
    @SerializedName("nether")
    NETHER,
    @SerializedName("ocean")
    OCEAN,
    @SerializedName("plains")
    PLAINS,
    @SerializedName("plateau")
    PLATEAU,
    @SerializedName("river")
    RIVER,
    @SerializedName("roofed")
    ROOFED,
    @SerializedName("savanna")
    SAVANNA,
    @SerializedName("shore")
    SHORE,
    @SerializedName("stone")
    STONE,
    @SerializedName("swamp")
    SWAMP,
    @SerializedName("taiga")
    TAIGA,
    @SerializedName("the_end")
    THE_END,
    @SerializedName("warm")
    WARM;
}