name: Monstera Build and Test

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: burrunan/gradle-cache-action@v1
        name: Build Monstera
        with:
          job-id: jdk11
          arguments: |
            build
            --warning-mode all
          gradle-version: wrapper